apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmg-vso-user-app-aws
  namespace: tmg-ksa-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmg-vso-user-app-aws
  template:
    metadata:
      labels:
        app: tmg-vso-user-app-aws
    spec:
      containers:
        - name: tmg-vso-user-app
          image: 559672757114.dkr.ecr.eu-west-3.amazonaws.com/tmg-vso-user-app:latest
          args:
            - --spring.application.json=$(BINDING)
          env:
            - name: BINDING
              valueFrom:
                configMapKeyRef:
                  name: backend-properties
                  key: application-properties
          ports:
            - containerPort: 8025
          resources:
            requests:
              memory: 350Mi
              cpu: 125m
      dnsPolicy: Default
---
apiVersion: v1
kind: Service
metadata:
  name: tmg-vso-user-service-cip-aws
  namespace: tmg-ksa-dev
  labels:
    app: tmg-vso-user-app-aws
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8025
  selector:
    app: tmg-vso-user-app-aws
